### ISSUE TITLE
Move StyleCI Config to Website

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#490]
StyleCI just added support to add the configuration directly on the repository on their website. I think that would be much better than having the `.styleci.yml` file. 

Maybe you could add it on the website @lucadegasperi? Here is an updated version:
```yaml
enabled:
  - unalign_double_arrow
  - unalign_equals

disabled:
  - psr0
  - align_double_arrow
  - phpdoc_align
```

Once you've added it I can remove the file from the repo. Let me know.

**Comment by lucadegasperi** [comment]
Done.

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
@lucadegasperi Maybe we should do the same with Scrutinizer?

**Comment by vinkla** [comment]
Sorry about this but we have to update the configuration again. They've pushed changes that will make our config to error. Use this one instead:

```yaml
enabled:
  - unalign_double_arrow

disabled:
  - psr0
  - align_double_arrow
  - phpdoc_align
```
